---
title: "Combining Search Term Data"
author: "Georgianna James"
date: '2022-05-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Required Packages 

```{r}
library(gtrendsR)
library(tidyverse)
library(lubridate)
library(stargazer)
library(here)

```


```{r}
# Visualizing further search terms 

further_search_terms <- read_csv(here("data", "further_terms.csv"))

further_search_terms
```
```{r}
# read in all search term data frames

hugging <- read_csv(here("data", "hugging.csv"))

bumble <- read_csv(here("data", "Bumble.csv"))

date_from_home <- read_csv(here("data", "date from home.csv"))

date_ideas <- read_csv(here("data", "Date ideas.csv"))

dating_apps <- read_csv(here("data", "Dating apps.csv"))

hinge <- read_csv(here("data", "Hinge.csv"))

hookups <- read_csv(here("data", "hookups.csv"))

hugging <- read_csv(here("data", "hugging.csv"))

intimacy <- read_csv(here("data", "Intimacy.csv"))

kissing <- read_csv(here("data", "kissing.csv"))

love <- read_csv(here("data", "love.csv"))

match <- read_csv(here("data", "Match.csv"))

online_dating <- read_csv(here("data", "online dating.csv"))

outdoor_dates <- read_csv(here("data", "Outdoor dates.csv"))

relationship <- read_csv(here("data", "Relationship.csv"))

romance <- read_csv(here("data", "Romance.csv"))

sex <- read_csv(here("data", "sex.csv"))

video_dating <- read_csv(here("data", "Video dating.csv"))


```

## Creating Pandemic Dating Terms Data Set

```{r}
# joining outdoor dates and date ideas
pandemic_dating <- full_join(outdoor_dates, date_ideas, by = "date") %>% 
  rename(outdoor_dates = hits.x, date_ideas = hits.y) %>% 
  select(date, outdoor_dates, date_ideas)
```

```{r}
# adding match to df
pandemic_dating <-full_join(pandemic_dating, match, by = "date")%>% 
  rename(match = hits) %>% 
   select(date, outdoor_dates, date_ideas, match)
```


```{r}
# adding romance column 

pandemic_dating <-full_join(pandemic_dating, romance, by = "date")%>% 
  rename(romance = hits) %>% 
   select(date, outdoor_dates, date_ideas, match, romance)
```

```{r}
# adding intimacy column

pandemic_dating <-full_join(pandemic_dating, intimacy, by = "date")%>% 
  rename(intimacy = hits) %>% 
   select(date, outdoor_dates, date_ideas, match, romance, intimacy)
```

```{r}
# adding video dating
pandemic_dating <-full_join(pandemic_dating, video_dating, by = "date")%>% 
  rename(video_dating = hits) %>% 
   select(date, outdoor_dates, date_ideas, match, romance, intimacy, video_dating)
```

```{r}
# adding relationships column
pandemic_dating <-full_join(pandemic_dating, relationship, by = "date") %>% 
  rename(relationships = hits) %>% 
   select(date, outdoor_dates, date_ideas, match, romance, intimacy, video_dating, relationships)
```

```{r}
# adding hookups columns

pandemic_dating <-full_join(pandemic_dating, hookups, by = "date") %>% 
    rename(hookups = hits) %>% 
   select(date, outdoor_dates, date_ideas, match, romance, intimacy, video_dating, relationships, hookups)
  
```

```{r}
# adding kissing columns

pandemic_dating <-full_join(pandemic_dating, kissing, by = "date") %>% 
    rename(kissing = hits) %>% 
   select(date, outdoor_dates, date_ideas, match, romance, intimacy, video_dating, relationships, hookups, kissing)
```

```{r}
# adding hugging column

pandemic_dating <-full_join(pandemic_dating, hugging, by = "date") %>% 
    rename(hugging = hits) %>% 
   select(date, outdoor_dates, date_ideas, match, romance, intimacy, video_dating, relationships, hookups, kissing, hugging)
```

```{r}
# adding sex column

pandemic_dating <-full_join(pandemic_dating, sex, by = "date") %>% 
    rename(sex = hits) %>% 
   select(date, outdoor_dates, date_ideas, match, romance, intimacy, video_dating, relationships, hookups, kissing, hugging, sex)
```

```{r}
# adding date from home column

pandemic_dating <-full_join(pandemic_dating, date_from_home, by = "date") %>% 
    rename(date_from_home = hits) %>% 
   select(date, outdoor_dates, date_ideas, match, romance, intimacy, video_dating, relationships, hookups, kissing, hugging, sex, date_from_home)
```

```{r}
# adding hinge column

pandemic_dating <-full_join(pandemic_dating, hinge, by = "date") %>% 
    rename(hinge = hits) %>% 
   select(date, outdoor_dates, date_ideas, match, romance, intimacy, video_dating, relationships, hookups, kissing, hugging, sex, date_from_home, hinge)
```

```{r}
# adding bumble column

pandemic_dating <-full_join(pandemic_dating, bumble, by = "date") %>% 
    rename(bumble = hits) %>% 
   select(date, outdoor_dates, date_ideas, match, romance, intimacy, video_dating, relationships, hookups, kissing, hugging, sex, date_from_home, hinge, bumble)
```


```{r}
# adding dating apps column

pandemic_dating <-full_join(pandemic_dating, dating_apps, by = "date") %>% 
    rename(dating_apps = hits) %>% 
   select(date, outdoor_dates, date_ideas, match, romance, intimacy, video_dating, relationships, hookups, kissing, hugging, sex, date_from_home, hinge, bumble, dating_apps)
```

```{r}
# adding love column

pandemic_dating <-full_join(pandemic_dating, love, by = "date") %>% 
    rename(love = hits) %>% 
   select(date, outdoor_dates, date_ideas, match, romance, intimacy, video_dating, relationships, hookups, kissing, hugging, sex, date_from_home, hinge, bumble, dating_apps, love)
```

```{r}
# add online dating column

pandemic_dating <-full_join(pandemic_dating, online_dating, by = "date") %>% 
    rename(online_dating = hits) %>% 
   select(date, outdoor_dates, date_ideas, match, romance, intimacy, video_dating, relationships, hookups, kissing, hugging, sex, date_from_home, hinge, bumble, dating_apps, love, online_dating)
```

```{r}

# save as a csv file

write.csv(pandemic_dating, here("data", "search_terms_full_dataset.csv"), row.names=TRUE)


```

```{r}

# combining all search data 

pandemic_dating_reg <- pandemic_dating %>% 
    mutate(
      total_hits = rowSums(select(., -date)),
    date= ymd(date),
    month = month(date),
    day = day(date),
    year = year(date)
        ) %>% 
  filter(
    date > ymd(20170811) & date < ymd(20180911) | date > ymd(20190811) & date < ymd(20200911)
    ) %>% 
  mutate(
    pandemic_dates = ifelse(date %within% interval(ymd(20170811), ymd(20180310)) | date %within% interval(ymd(20190811), ymd(20200310)), 0, 1),
    pandemic_year = ifelse(year == 2017 | year == 2018, 0, 1),
    pandemic = ifelse(pandemic_dates == 1 & pandemic_year == 1, 1, 0)
  )

pandemic_dating_reg
```
```{r}

# regress using total hits

total_hits_regression <- lm(total_hits ~ pandemic, data = pandemic_dating_reg)

stargazer(total_hits_regression,
           type = "text",
            title="Search Term Regression Table", 
  dep.var.labels= "Total Hits",
  covariate.labels=c("Pandemic", "No Pandemic"),
  digits=3, out = glue::glue("totalhits.txt"))
```


