---
title: 'Romantic Connection During a Public Health Crisis: What Do Internet-Search
  Rates Tell Us?'
author: "Georgianna James"
date: '2022-05-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Pandemic Dating and Google Trends


## Required Packages 

```{r}
library(gtrendsR)
library(tidyverse)
library(lubridate)
library(stargazer)
library(here)

```

## "Online Dating" Data Collection

```{r}
# create a data folder 

dir.create("data")

# create a terms df 

term <- c("online dating", 
           "love", 
           "Dating apps",
           "Bumble", 
           "Hinge",
           "date from home",
           "sex",
           "hugging",
           "kissing",
           "hookups",
           "Relationship",
           "Video dating",
           "Intimacy",
           "Romance",
           "Match",
           "Date ideas",
           "Outdoor dates"
           )

terms_df <- as_tibble(term)

write.csv(terms_df, here("data", "search_terms.csv"), row.names=TRUE)


```


```{r}
# test out g trends function

onlinedating <- gtrends(
  c('online dating'),
  geo='US')

saveRDS(onlinedating, here("data", "onlinedating.RDS"))

#Plot
plot(onlinedating)

```
```{r}
# create a df to put all related queries in one df

additional_terms <- onlinedating$related_queries %>% 
  select(value)
  

further_terms <- rbind(terms_df, additional_terms)

write.csv(further_terms, here("data", "further_terms.csv"), row.names=TRUE)
```






